### ISSUE TITLE
make Python 3 compatible

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/numkit#1]
Should work under Python 2.7 and Python 3.x (at least ≥ 3.4)

- [ ] use `six` for 2/3 compatibility
- [ ] add Py 3 to travis test matrix
- [ ] test with Python 3 should pass

**Comment by kain88-de** [comment]
If you do a release this will make testing your gromacswrapper easier. Currently, it will fail also because the version on pip is not python 3 ready.
