### ISSUE TITLE
distribute as conda package

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/numkit#6]
In order to solve https://github.com/Becksteinlab/GromacsWrapper/issues/109 we also need numkit as a conda package (conda-forge or bioconda).

**Comment by orbeckst** [comment]
@kain88-de do you have any advice as to where numkit should go – conda-forge or bioconda?

**Comment by kain88-de** [comment]
Conda forge. They have automated updates of packages soon.

**Comment by orbeckst** [comment]
@simonbray created conda packages as part of  Becksteinlab/GromacsWrapper#109 — thank you!!
